pub mod doctor;
mod doctor_presentation;
pub mod index;
mod index_dashboard;
pub mod list;
pub mod locate;
pub mod search;
pub mod show;
pub mod sources;
pub mod stats;
pub mod status;
mod status_health;
mod status_presentation;

pub use doctor::DoctorArgs;
pub use doctor_presentation::{render_doctor_human, source_epoch_findings};
pub use index::IndexArgs;
pub use list::{ListArgs, ListEventsArgs, ListTarget};
pub use locate::{LocateArgs, LocateTarget};
pub use search::{CliRefreshArg, ContentScopeArg, SearchArgs, SearchBackendArg};
pub use setup::SetupArgs;
pub use show::{ShowArgs, ShowEventArgs, ShowSessionArgs, ShowTarget};
pub use sources::SourcesArgs;
pub use stats::StatsArgs;
pub use status::{StatusArgs, UsageStatusMode};
pub use status_presentation::render_status_human;
pub mod setup;
