pub(crate) mod astrbot;
pub(crate) mod auggie;
pub(crate) mod codebuddy;
pub(crate) mod continue_cli;
pub(crate) mod crush;
pub(crate) mod deepagents;
pub(crate) mod firebender;
pub(crate) mod forgecode;
#[cfg(test)]
mod gemini;
pub(crate) mod goose;
pub(crate) mod hermes;
pub(crate) mod kiro;
pub(crate) mod lingma;
pub(crate) mod nanoclaw;
pub(crate) mod opencode;
pub(crate) mod openhands;
pub(crate) mod rovodev;
pub(crate) mod shelley;
pub(crate) mod task_json;
pub(crate) mod trae;
pub(crate) mod warp;
pub(crate) mod zed;
